export const GET_PROJECT_LIST ="GET_PROJECT_LIST";
export const POST_PROJECT_LIST = "POST_PROJECT_LIST";
export const USER_BY_DESIGNATION ="USER_BY_DESIGNATION";
export const GET_TECHNOLOGY ="GET_TECHNOLOGY";