export const EMPLOYEE_DETAILS = "EMPLOYEE_DETAILS";
export const EMPLOYEE_LIST ="EMPLOYEE_LIST";
export const ADD_EMPLOYEE ="ADD_EMPLOYEE";
export const UPDATE_EMPLOYEE ="UPDATE_EMPLOYEE";
export const GET_DESIGNATION ="GET_DESIGNATION";
export const GET_BRANCH_LIST ="GET_BRANCH_LIST";
export const GET_USER_BY_DESIGNATION_ID ="GET_USER_BY_DESIGNATION_ID";